org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.20
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=hygiene
mod_name=Hygiene Mod
mod_license=CC BY-NC-ND 4.0
mod_version=1.0.6
mod_group_id=com.hygienemod
mod_authors=Akirabane
mod_description=Système d hygiene viking pour serveur RP Minecraft.
